version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.app
        command: nginx -g "daemon off;"
        links:
            - app
        ports:
            - "${APP_PORT}:80"
        
    app:
        build: 
            context: ./docker
            dockerfile: app.app
        volumes:
            - .:/var/www
        working_dir: /var/www/public
        command: php-fpm
        links:
            - db
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    db:
        image: mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
